/*
	Copyright (c) 2015 Denis Zykov

	This is part of Charon Game Data Editor Unity Plugin.

	Charon Game Data Editor Unity Plugin is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see http://www.gnu.org/licenses.
*/
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace GameDevWare.Charon
{
	public static class Resources
	{
		public const string UI_UNITYPLUGIN_ATTACH_FILE_BUTTON = "Attach...";
		public const string UI_UNITYPLUGIN_DOWNLOAD_BUTTON = "Update (~{0:F1} MiB)";
		public const string UI_UNITYPLUGIN_GENERATE_ASSET_CANT_FIND_GAMEDATA_CLASS = "Asset generation failed: unable to find GameData's type in CSharp assemblies. Make sure there is no compilation errors.";
		public const string UI_UNITYPLUGIN_GENERATE_CODE_FOR = "Running generation tools for {0}";
		public const string UI_UNITYPLUGIN_GENERATE_FAILED_DUE_ERRORS = "Code generation for '{0}' failed due errors: {1}.";
		public const string UI_UNITYPLUGIN_GENERATE_REFORMAT_CODE = "Re-formatting generated code for {0}";
		public const string UI_UNITYPLUGIN_GENERATE_REFRESHING_ASSETS = "Refreshing assets";
		public const string UI_UNITYPLUGIN_GENERATING_CODE_AND_ASSETS = "Generating Code and Assets...";
		public const string UI_UNITYPLUGIN_MENU_ABOUT = "About...";
		public const string UI_UNITYPLUGIN_MENU_CHECK_RUNTIME = "Check Runtime Version...";
		public const string UI_UNITYPLUGIN_MENU_CHECK_UPDATES = "Check for Updates";
		public const string UI_UNITYPLUGIN_MENU_CREATE_GAMEDATA_JSON = "Game Data (JSON)";
		public const string UI_UNITYPLUGIN_MENU_DOCUMENTATION = "Documentation (website)";
		public const string UI_UNITYPLUGIN_MENU_EXTRACT_T4_TEMPLATES = "Extract T4 Templates";
		public const string UI_UNITYPLUGIN_MENU_GENERATE_CODE_AND_ASSETS = "Generate Code and Assets";
		public const string UI_UNITYPLUGIN_MENU_OPEN_LOGS = "Open Logs";
		public const string UI_UNITYPLUGIN_MENU_RECOVERY_SCRIPTS = "Recovery Scripts";
		public const string UI_UNITYPLUGIN_MENU_REPORT_ISSUE = "Report an Issue...";
		public const string UI_UNITYPLUGIN_MENU_TROUBLESHOOTING = "Troubleshooting";
		public const string UI_UNITYPLUGIN_MENU_VALIDATE_ASSETS = "Validate Assets";
		public const string UI_UNITYPLUGIN_MENU_VERBOSE_LOGS = "Verbose Logs";
		public const string UI_UNITYPLUGIN_MIGRATE_RUN_MIGRATION_FOR = "Running migration tools for {0}";
		public const string UI_UNITYPLUGIN_OPERATION_CANCELLED = "Operation was cancelled by user.";
		public const string UI_UNITYPLUGIN_PROGRESS_CHECKING_TOOLS_VERSION = "Checking current tools version...";
		public const string UI_UNITYPLUGIN_PROGRESS_CURRENT_TARGET_IS = "Current target is {0}";
		public const string UI_UNITYPLUGIN_PROGRESS_DONE = "Done";
		public const string UI_UNITYPLUGIN_PROGRESS_DOWNLOADINGS = "Downloading assets ({0:F2}/{1:F2}Mib)...";
		public const string UI_UNITYPLUGIN_PROGRESS_GETTING_AVAILABLE_BUILDS = "Getting list of public releases...";
		public const string UI_UNITYPLUGIN_REPORT_BUTTON = "Report";
		public const string UI_UNITYPLUGIN_SCAN_RUN_VALIDATION_FOR = "Running validation tool for {0}";
		public const string UI_UNITYPLUGIN_SELECT_FILE_TO_ATTACH_TITLE = "Select file to attach";
		public const string UI_UNITYPLUGIN_SPECIFY_EXTRACTION_LOC_TITLE = "Specify extraction location...";
		public const string UI_UNITYPLUGIN_T4_EXTRACTION_COMPLETE = "T4 Template extracted successfully.";
		public const string UI_UNITYPLUGIN_T4_EXTRACTION_FAILED = "T4 Template extraction failed due errors: {0}";
		public const string UI_UNITYPLUGIN_UPDATE_AVAILABLE_MESSAGE = "A new vesion '{1}' of {2} available. Current version is '{0}'.";
		public const string UI_UNITYPLUGIN_UPDATE_AVAILABLE_TITLE = "Update Available";
		public const string UI_UNITYPLUGIN_VALIDATE_COMPLETE = "Validation of '{0}' is complete. Result: {1}, Errors: {2}.";
		public const string UI_UNITYPLUGIN_VALIDATE_FAILED_DUE_ERRORS = "Validation of '{0}' has failed due errors: {1}.";
		public const string UI_UNITYPLUGIN_VALIDATE_RUN_FOR = "Running validation tool for {0}";
		public const string UI_UNITYPLUGIN_VALIDATING_ASSETS = "Validating Assets...";
		public const string UI_UNITYPLUGIN_WINDOW_ABOUT_CHARON_TITLE = "Charon: Game Data Editor";
		public const string UI_UNITYPLUGIN_WINDOW_ACTIONS_GROUP = "Actions";
		public const string UI_UNITYPLUGIN_WINDOW_ASSET_GENERATION_PATH = "Asset Generation Path";
		public const string UI_UNITYPLUGIN_WINDOW_ATTACH_FILE_CHECKBOX = "Attach '{0}' file ({1:F2}Mb)";
		public const string UI_UNITYPLUGIN_WINDOW_AUTO_GENERATION = "Auto-Generation";
		public const string UI_UNITYPLUGIN_WINDOW_BACK_BUTTON = "Back";
		public const string UI_UNITYPLUGIN_WINDOW_BROWSE_BUTTON = "Browse...";
		public const string UI_UNITYPLUGIN_WINDOW_BROWSER = "Browser";
		public const string UI_UNITYPLUGIN_WINDOW_BROWSER_PATH = "Browser Path";
		public const string UI_UNITYPLUGIN_WINDOW_BROWSER_PATH_TITLE = "Path to browser application";
		public const string UI_UNITYPLUGIN_WINDOW_CANCEL_BUTTON = "Cancel";
		public const string UI_UNITYPLUGIN_WINDOW_CHECK_RESULT_MISSING_MONO_OR_DOTNET = "Missing .NET Runtime!";
		public const string UI_UNITYPLUGIN_WINDOW_CHECKING_MONO = "Checking Mono...";
		public const string UI_UNITYPLUGIN_WINDOW_CHECKING_MONO_FAILED = "Mono doesn't return any version information. Exit code: {0}";
		public const string UI_UNITYPLUGIN_WINDOW_CHECKING_VERSION = "Checking...";
		public const string UI_UNITYPLUGIN_WINDOW_CODE_API_CLASS_NAME = "API Class";
		public const string UI_UNITYPLUGIN_WINDOW_CODE_DOCUMENT_CLASS_NAME = "Document Class";
		public const string UI_UNITYPLUGIN_WINDOW_CODE_GENERATION_PATH = "Generation Path";
		public const string UI_UNITYPLUGIN_WINDOW_CODE_GENERATOR = "Code Generator";
		public const string UI_UNITYPLUGIN_WINDOW_CODE_INDENTATION = "Indentation";
		public const string UI_UNITYPLUGIN_WINDOW_CODE_LINE_ENDINGS = "Line Endings";
		public const string UI_UNITYPLUGIN_WINDOW_CODE_NAMESPACE = "Namespace";
		public const string UI_UNITYPLUGIN_WINDOW_CODE_OPTIONS = "Options";
		public const string UI_UNITYPLUGIN_WINDOW_DOWNLOAD_DOTNET = "c) Or you can download  .NET 4.5 by pressing 'Download .NET 4.5'.";
		public const string UI_UNITYPLUGIN_WINDOW_DOWNLOAD_DOTNET_BUTTON = "Download .NET 4.5";
		public const string UI_UNITYPLUGIN_WINDOW_DOWNLOAD_MONO = "b) If it doesn't exists you can press 'Download Mono' button below and try again.";
		public const string UI_UNITYPLUGIN_WINDOW_DOWNLOAD_MONO_BUTTON = "Download Mono";
		public const string UI_UNITYPLUGIN_WINDOW_EDIT_BUTTON = "Edit";
		public const string UI_UNITYPLUGIN_WINDOW_EDITOR_CHECKING_RUNTIME = "Checking runtime and executable...";
		public const string UI_UNITYPLUGIN_WINDOW_EDITOR_COPYING_EXECUTABLE = "Making shadow copy of tools";
		public const string UI_UNITYPLUGIN_WINDOW_EDITOR_LAUNCHING_EXECUTABLE = "Launching editor's executable...";
		public const string UI_UNITYPLUGIN_WINDOW_EDITOR_OPENING_BROWSER = "Opening brower...";
		public const string UI_UNITYPLUGIN_WINDOW_EDITOR_TITLE = "Editor";
		public const string UI_UNITYPLUGIN_WINDOW_EXPIRATION = "Expiration";
		public const string UI_UNITYPLUGIN_WINDOW_FAILED_TO_START_EDITOR = "Failed to start Game Data editor due errors:";
		public const string UI_UNITYPLUGIN_WINDOW_FAILED_TO_START_EDITOR_TIMEOUT = "Failed to start Game Data editor due errors: Aborted by timeout.";
		public const string UI_UNITYPLUGIN_WINDOW_FIND_MONO_MANUALLY = "a) You can manually locate Mono Runtime by pressing 'Browse...' button.";
		public const string UI_UNITYPLUGIN_WINDOW_FIRST_NAME = "First Name";
		public const string UI_UNITYPLUGIN_WINDOW_GENERATION_PREFIX = "Generation:";
		public const string UI_UNITYPLUGIN_WINDOW_HELP_BUTTON = "Help";
		public const string UI_UNITYPLUGIN_WINDOW_INFO_GROUP = "Info:";
		public const string UI_UNITYPLUGIN_WINDOW_KILL_PROCESS_BUTTON = "Kill Process";
		public const string UI_UNITYPLUGIN_WINDOW_LAST_NAME = "Last Name";
		public const string UI_UNITYPLUGIN_WINDOW_LAST_TOOLS_VERSION_LABEL = "Last Tools Version";
		public const string UI_UNITYPLUGIN_WINDOW_LICENSE_ACTIVATION_TITLE = "Charon License Activation";
		public const string UI_UNITYPLUGIN_WINDOW_LOADING_FAILED_WITH_ERROR = "Loading failed with error: {0}";
		public const string UI_UNITYPLUGIN_WINDOW_OK_BUTTON = "Ok";
		public const string UI_UNITYPLUGIN_WINDOW_PATH_TO_MONO = "Path to Mono (bin)";
		public const string UI_UNITYPLUGIN_WINDOW_PRESS_HELP = "If you need a help with .NET Runtime installation press 'Help' button.";
		public const string UI_UNITYPLUGIN_WINDOW_RE_CHECK_BUTTON = "Re-check";
		public const string UI_UNITYPLUGIN_WINDOW_RECIPIENT_ID = "Recipient Id";
		public const string UI_UNITYPLUGIN_WINDOW_RELOAD_BUTTON = "Reload";
		public const string UI_UNITYPLUGIN_WINDOW_REPORT_ISSUE_TITLE = "Report an Issue";
		public const string UI_UNITYPLUGIN_WINDOW_REPORT_THANKS_MESSAGE = "Thank you for your feedback!";
		public const string UI_UNITYPLUGIN_WINDOW_REPORTER_LABEL = "Your E-Mail or Name";
		public const string UI_UNITYPLUGIN_WINDOW_RUN_GENERATOR_BUTTON = "Run Generator";
		public const string UI_UNITYPLUGIN_WINDOW_RUNTIME_REQUIRED = "To run Game Data Editor and related tools you need a installed .NET Runtime or Mono Runtime.";
		public const string UI_UNITYPLUGIN_WINDOW_RUNTIME_VERSION = "Runtime Version";
		public const string UI_UNITYPLUGIN_WINDOW_RUNTIME_VERSION_ERROR = "Error";
		public const string UI_UNITYPLUGIN_WINDOW_RUNTIME_VERSION_UNKNOWN = "Unknown";
		public const string UI_UNITYPLUGIN_WINDOW_SETTINGS_GROUP = "Settings:";
		public const string UI_UNITYPLUGIN_WINDOW_TOOLS_PATH = "Tools Path";
		public const string UI_UNITYPLUGIN_WINDOW_TOOLS_PORT = "Tools Port";
		public const string UI_UNITYPLUGIN_WINDOW_TOOLS_VERSION_LABEL = "Tools Version";
		public const string UI_UNITYPLUGIN_WINDOW_TYPE = "Type";
		public const string UI_UNITYPLUGIN_WINDOW_TYPE_LABEL = "Type";
		public const string UI_UNITYPLUGIN_WINDOW_UPDATE_RUNTIME_TITLE = ".NET Runtime Update";
		public const string UI_UNITYPLUGIN_WINDOW_UPDATE_TOOLS_TITLE = "Tools Update";
		public const string UI_UNITYPLUGIN_WINDOW_VALIDATE_BUTTON = "Validate";
		public const string UI_UNITYPLUGIN_WINDOW_VALIDATION_PREFIX = "Validation:";
		public const string UI_UNITYPLUGIN_WINDOWCHECK_RESULT_MISSING_TOOLS = "Missing Tools!";
		public const string UI_UNITYPLUGIN_WINDOWE_MAIL = "Email";
	}
}

