/*
	Copyright (c) 2016 Denis Zykov

	This is part of "Charon: Game Data Editor" Unity Plugin.

	Charon Game Data Editor Unity Plugin is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see http://www.gnu.org/licenses.
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
// ReSharper disable once EmptyNamespace
namespace Assets.Editor.GameDevWare.Charon
{

	public class Resources
	{
#if CHARON_RU
        public const string LANGUAGE = "ru";
        public const string UI_UNITYPLUGIN_GENERATEASSETCANTFINDGAMEDATACLASS = "Asset generation failed: unable to find GameData's type in CSharp assemblies. Make sure there is no compilation errors.";
        public const string UI_UNITYPLUGIN_GENERATECODEFOR = "Running generation tools for {0}";
        public const string UI_UNITYPLUGIN_GENERATEFAILEDDUEERRORS = "Code generation for '{0}' failed due errors: {1}.";
        public const string UI_UNITYPLUGIN_GENERATEREFORMATCODE = "Re-formatting generated code for {0}";
        public const string UI_UNITYPLUGIN_GENERATEREFRESHINGASSETS = "Refreshing assets";
        public const string UI_UNITYPLUGIN_GENERATINGCODEANDASSETS = "Generating Code and Assets...";
        public const string UI_UNITYPLUGIN_MENUSCANNINGASSETS = "Scanning Assets...";
        public const string UI_UNITYPLUGIN_MIGRATERUNMIGRATIONFOR = "Running migration tools for {0}";
        public const string UI_UNITYPLUGIN_PROGRESSCURRENTTARGETIS = "Current target is {0}";
        public const string UI_UNITYPLUGIN_PROGRESSDONE = "Done";
        public const string UI_UNITYPLUGIN_SCANASSETSKIPPED = "TextAsset '{0}' is skipped because of validation error.";
        public const string UI_UNITYPLUGIN_SCANCOMPLETE = "Scan complete: {0} files are located. Total {1} files are tracked.";
        public const string UI_UNITYPLUGIN_SCANRUNVALIDATIONFOR = "Running validation tool for {0}";
        public const string UI_UNITYPLUGIN_SPECIFYEXTRACTIONLOCTITLE = "Specify extraction location...";
        public const string UI_UNITYPLUGIN_T4EXTRACTIONCOMPLETE = "T4 Template extracted successfully.";
        public const string UI_UNITYPLUGIN_T4EXTRACTIONFAILED = "T4 Template extraction failed due errors: {0}";
        public const string UI_UNITYPLUGIN_VALIDATECOMPLETE = "Validation of '{0}' is complete. Result: {1}, Errors: {2}.";
        public const string UI_UNITYPLUGIN_VALIDATEFAILEDDUEERRORS = "Validation of '{0}' has failed due errors: {1}.";
        public const string UI_UNITYPLUGIN_VALIDATERUNFOR = "Running validation tool for {0}";
        public const string UI_UNITYPLUGIN_VALIDATINGASSETS = "Validating Assets...";
        public const string UI_UNITYPLUGIN_MENUABOUT = "About...";
        public const string UI_UNITYPLUGIN_MENUDOCUMENTATION = "Documentation (website)";
        public const string UI_UNITYPLUGIN_MENUEXTRACTT4TEMPLATES = "Extract T4 Templates";
        public const string UI_UNITYPLUGIN_MENUGENERATECODEANDASSETS = "Generate Code and Assets";
        public const string UI_UNITYPLUGIN_MENURECOVERYSCRIPTS = "Recovery Scripts";
        public const string UI_UNITYPLUGIN_MENUSCANFORNEWASSETS = "Scan for new Assets";
        public const string UI_UNITYPLUGIN_MENUREPORTISSUE = "Report an Issue...";
        public const string UI_UNITYPLUGIN_MENUTROUBLESHOOTING = "Troubleshooting";
        public const string UI_UNITYPLUGIN_MENUVALIDATEASSETS = "Validate Assets";
        public const string UI_UNITYPLUGIN_MENUVERBOSELOGS = "Verbose Logs";
        public const string UI_UNITYPLUGIN_OPERATIONCANCELLED = "Operation was cancelled by user.";
        public const string UI_UNITYPLUGIN_WINDOWABOUTCHARONTITLE = "Charon: Game Data Editor";
        public const string UI_UNITYPLUGIN_WINDOWACTIONSGROUP = "Actions";
        public const string UI_UNITYPLUGIN_WINDOWASSETGENERATIONPATH = "Asset Generation Path";
        public const string UI_UNITYPLUGIN_WINDOWAUTOGENERATION = "Auto-Generation";
        public const string UI_UNITYPLUGIN_WINDOWBROWSEBUTTON = "Browse...";
        public const string UI_UNITYPLUGIN_WINDOWBROWSER = "Browser";
        public const string UI_UNITYPLUGIN_WINDOWBROWSERPATH = "Browser Path";
        public const string UI_UNITYPLUGIN_WINDOWBROWSERPATHTITLE = "Path to browser application";
        public const string UI_UNITYPLUGIN_WINDOWCANCELBUTTON = "Cancel";
        public const string UI_UNITYPLUGIN_WINDOWCHECKINGMONO = "Checking Mono...";
        public const string UI_UNITYPLUGIN_WINDOWCHECKINGMONOFAILED = "Mono doesn't return any version information. Exit code: {0}";
        public const string UI_UNITYPLUGIN_WINDOWCHECKINGVERSION = "Checking...";
        public const string UI_UNITYPLUGIN_WINDOWCHECKRESULTMISSINGMONOORDOTNET = "Missing .NET Runtime!";
        public const string UI_UNITYPLUGIN_WINDOWCHECKRESULTMISSINGTOOLS = "Missing Tools!";
        public const string UI_UNITYPLUGIN_WINDOWCODEENTRYCLASSNAME = "Code Entry class";
        public const string UI_UNITYPLUGIN_WINDOWCODEGAMEDATACLASSNAME = "Code GameData class";
        public const string UI_UNITYPLUGIN_WINDOWCODEGENERATIONPATH = "Code Generation Path";
        public const string UI_UNITYPLUGIN_WINDOWCODEGENERATOR = "Code Generator";
        public const string UI_UNITYPLUGIN_WINDOWCODEIDENTATION = "Identation";
        public const string UI_UNITYPLUGIN_WINDOWCODELINEENDINGS = "Line endings";
        public const string UI_UNITYPLUGIN_WINDOWCODENAMESPACE = "Code Namespace";
        public const string UI_UNITYPLUGIN_WINDOWCODEOPTIONS = "Options";
        public const string UI_UNITYPLUGIN_WINDOWDOWNLOADDOTNET = "c) Or you can download  .NET 4.5 by pressing 'Download .NET 4.5'.";
        public const string UI_UNITYPLUGIN_WINDOWDOWNLOADDOTNETBUTTON = "Download .NET 4.5";
        public const string UI_UNITYPLUGIN_WINDOWDOWNLOADMONO = "b) If it doesn't exists you can press 'Download Mono' button below and try again.";
        public const string UI_UNITYPLUGIN_WINDOWDOWNLOADMONOBUTTON = "Download Mono";
        public const string UI_UNITYPLUGIN_WINDOWEDITBUTTON = "Edit";
        public const string UI_UNITYPLUGIN_WINDOWEDITORCHECKINGRUNTIME = "Checking runtime and executable...";
        public const string UI_UNITYPLUGIN_WINDOWEDITORCHECKINGLICENSE = "Checking license...";
        public const string UI_UNITYPLUGIN_WINDOWEDITORTITLE = "Editor";
        public const string UI_UNITYPLUGIN_WINDOWEDITORCOPYINGEXECUTABLE = "Copying executable to Temp directory...";
        public const string UI_UNITYPLUGIN_WINDOWFAILEDTOSTARTEDITOR = "Failed to start Game Data editor due errors:";
        public const string UI_UNITYPLUGIN_WINDOWFAILEDTOSTARTEDITORTIMEOUT = "Failed to start Game Data editor due errors: Aborted by timeout.";
        public const string UI_UNITYPLUGIN_WINDOWFINDMONOMANUALLY = "a) You can manually locate Mono Runtime by pressing 'Browse...' button.";
        public const string UI_UNITYPLUGIN_WINDOWGENERATIONPREFIX = "Generation:";
        public const string UI_UNITYPLUGIN_WINDOWHELPBUTTON = "Help";
        public const string UI_UNITYPLUGIN_WINDOWIMPORTLICENSEBUTTON = "Import";
        public const string UI_UNITYPLUGIN_WINDOWINFOGROUP = "Info:";
        public const string UI_UNITYPLUGIN_WINDOWLICENSEHOLDER = "License Holder";
        public const string UI_UNITYPLUGIN_WINDOWLICENSEKEY = "License Key";
        public const string UI_UNITYPLUGIN_WINDOWLOADINGFAILEDWITHERROR = "Loading failed with error: {0}";
        public const string UI_UNITYPLUGIN_WINDOWOKBUTTON = "Ok";
        public const string UI_UNITYPLUGIN_WINDOWPATHTOMONO = "Path to Mono (bin)";
        public const string UI_UNITYPLUGIN_WINDOWPRESSHELP = "If you need a help with .NET Runtime installation press 'Help' button.";
        public const string UI_UNITYPLUGIN_WINDOWRECHECKBUTTON = "Re-check";
        public const string UI_UNITYPLUGIN_WINDOWRELOADBUTTON = "Reload";
        public const string UI_UNITYPLUGIN_WINDOWRESUMECODERECOMPILATION = "Resume code re-compilation?";
        public const string UI_UNITYPLUGIN_WINDOWRUNGENERATORBUTTON = "Run Generator";
        public const string UI_UNITYPLUGIN_WINDOWRUNTIMEREQUIRED = "To run Game Data Editor and related tools you need a installed .NET Runtime or Mono Runtime.";
        public const string UI_UNITYPLUGIN_WINDOWRUNTIMEVERSION = "Runtime Version";
        public const string UI_UNITYPLUGIN_WINDOWRUNTIMEVERSIONERROR = "Error";
        public const string UI_UNITYPLUGIN_WINDOWRUNTIMEVERSIONUNKNOWN = "Unknown";
        public const string UI_UNITYPLUGIN_WINDOWSETTINGSGROUP = "Settings:";
        public const string UI_UNITYPLUGIN_WINDOWTOOLSPATH = "Tools Path";
        public const string UI_UNITYPLUGIN_WINDOWTOOLSPORT = "Tools Port";
        public const string UI_UNITYPLUGIN_WINDOWTOOLSVERSIONLABEL = "Tools Version";
        public const string UI_UNITYPLUGIN_WINDOWUNTRACTBUTTON = "Untrack";
        public const string UI_UNITYPLUGIN_WINDOWUPDATERUNTIMETITLE = ".NET Runtime Update";
        public const string UI_UNITYPLUGIN_WINDOWUPDATETOOLSTITLE = "Tools Update";
        public const string UI_UNITYPLUGIN_WINDOWVALIDATEBUTTON = "Validate";
        public const string UI_UNITYPLUGIN_WINDOWVALIDATIONPREFIX = "Validation:";
        public const string UI_UNITYPLUGIN_MENUCHECKRUNTIME = "Check Runtime Version...";
        public const string UI_UNITYPLUGIN_WINDOWLASTTOOLSVERSIONLABEL = "Last Tools Version";
        public const string UI_UNITYPLUGIN_MENUCHECKUPDATES = "Check for Updates";
        public const string UI_UNITYPLUGIN_PROGRESSCHECKINGTOOLSVERSION = "Checking current tools version...";
        public const string UI_UNITYPLUGIN_PROGRESSDOWNLOADINGS = "Downloading assets ({0:F2}/{1:F2}Mib)...";
        public const string UI_UNITYPLUGIN_PROGRESSGETTINGAVAILABLEBUILDS = "Getting list of public releases...";
        public const string UI_UNITYPLUGIN_ATTACHFILEBUTTON = "Attach...";
        public const string UI_UNITYPLUGIN_SELECTFILETOATTACHTITLE = "Select file to attach";
        public const string UI_UNITYPLUGIN_REPORTBUTTON = "Report";
        public const string UI_UNITYPLUGIN_WINDOWATTACHFILECHECKBOX = "Attach '{0}' file ({1:F2}Mb)";
        public const string UI_UNITYPLUGIN_WINDOWREPORTERLABEL = "Your E-Mail or Name";
        public const string UI_UNITYPLUGIN_WINDOWREPORTISSUETITLE = "Report an Issue";
        public const string UI_UNITYPLUGIN_WINDOWTYPELABEL = "Type";
        public const string UI_UNITYPLUGIN_WINDOWREPORTTHANKSMESSAGE = "Thank you for your feedback!";
        public const string UI_UNITYPLUGIN_DOWNLOADBUTTON = "Update (~10 MiB)";
        public const string UI_UNITYPLUGIN_UPDATEAVAILABLEMESSAGE = "A new vesion '{1}' of tools available. Current version is '{0}'.";
        public const string UI_UNITYPLUGIN_UPDATEAVAILABLETITLE = "Update Charon";
        public const string UI_UNITYPLUGIN_WINDOWASSETSTOREINVOICENUMBER = "Asset Store Invoice Number";
        public const string UI_UNITYPLUGIN_WINDOWBACKBUTTON = "Back";
        public const string UI_UNITYPLUGIN_WINDOWEMAIL = "Email";
        public const string UI_UNITYPLUGIN_WINDOWEXPIRATION = "Expiration";
        public const string UI_UNITYPLUGIN_WINDOWFIRSTNAME = "First Name";
        public const string UI_UNITYPLUGIN_WINDOWLASTNAME = "Last Name";
        public const string UI_UNITYPLUGIN_WINDOWLICENSEACTIVATIONTITLE = "Charon License Activation";
        public const string UI_UNITYPLUGIN_WINDOWNOAVAILABLELICENSESMESSAGE = "No available licenses.";
        public const string UI_UNITYPLUGIN_WINDOWORGANIZATION = "Organization";
        public const string UI_UNITYPLUGIN_WINDOWORGANIZATIONID = "Organization Id";
        public const string UI_UNITYPLUGIN_WINDOWPASSWORD = "Password";
        public const string UI_UNITYPLUGIN_WINDOWPASSWORDSDOESNMATCHMESSAGE = "Password does not match.";
        public const string UI_UNITYPLUGIN_WINDOWRECIPIENTID = "Recipient Id";
        public const string UI_UNITYPLUGIN_WINDOWREGISTERBUTTON = "Register";
        public const string UI_UNITYPLUGIN_WINDOWRETYPEPASSWORD = "Re-Type Password";
        public const string UI_UNITYPLUGIN_WINDOWSELECTLICENSELABEL = "Select License";
        public const string UI_UNITYPLUGIN_WINDOWSERIALNUMBER = "Serial Number";
        public const string UI_UNITYPLUGIN_WINDOWSIGNINBUTTON = "Sign In";
        public const string UI_UNITYPLUGIN_WINDOWTYPE = "Type";
        public const string UI_UNITYPLUGIN_WINDOWEDITORLAUNCHINGEXECUTABLE = "Launching editor's executable...";
        public const string UI_UNITYPLUGIN_WINDOWEDITOROPENINGBROWSER = "Opening brower...";
        public const string UI_UNITYPLUGIN_CHANGEBUTTON = "Change...";
        public const string UI_UNITYPLUGIN_MENUOPENLOGS = "Open Logs";
#else
		public const string LANGUAGE = "en";
		public const string UI_UNITYPLUGIN_GENERATEASSETCANTFINDGAMEDATACLASS = "Asset generation failed: unable to find GameData's type in CSharp assemblies. Make sure there is no compilation errors.";
		public const string UI_UNITYPLUGIN_GENERATECODEFOR = "Running generation tools for {0}";
		public const string UI_UNITYPLUGIN_GENERATEFAILEDDUEERRORS = "Code generation for '{0}' failed due errors: {1}.";
		public const string UI_UNITYPLUGIN_GENERATEREFORMATCODE = "Re-formatting generated code for {0}";
		public const string UI_UNITYPLUGIN_GENERATEREFRESHINGASSETS = "Refreshing assets";
		public const string UI_UNITYPLUGIN_GENERATINGCODEANDASSETS = "Generating Code and Assets...";
		public const string UI_UNITYPLUGIN_MENUSCANNINGASSETS = "Scanning Assets...";
		public const string UI_UNITYPLUGIN_MIGRATERUNMIGRATIONFOR = "Running migration tools for {0}";
		public const string UI_UNITYPLUGIN_PROGRESSCURRENTTARGETIS = "Current target is {0}";
		public const string UI_UNITYPLUGIN_PROGRESSDONE = "Done";
		public const string UI_UNITYPLUGIN_SCANASSETSKIPPED = "TextAsset '{0}' is skipped because of validation error.";
		public const string UI_UNITYPLUGIN_SCANCOMPLETE = "Scan complete: {0} files are located. Total {1} files are tracked.";
		public const string UI_UNITYPLUGIN_SCANRUNVALIDATIONFOR = "Running validation tool for {0}";
		public const string UI_UNITYPLUGIN_SPECIFYEXTRACTIONLOCTITLE = "Specify extraction location...";
		public const string UI_UNITYPLUGIN_T4EXTRACTIONCOMPLETE = "T4 Template extracted successfully.";
		public const string UI_UNITYPLUGIN_T4EXTRACTIONFAILED = "T4 Template extraction failed due errors: {0}";
		public const string UI_UNITYPLUGIN_VALIDATECOMPLETE = "Validation of '{0}' is complete. Result: {1}, Errors: {2}.";
		public const string UI_UNITYPLUGIN_VALIDATEFAILEDDUEERRORS = "Validation of '{0}' has failed due errors: {1}.";
		public const string UI_UNITYPLUGIN_VALIDATERUNFOR = "Running validation tool for {0}";
		public const string UI_UNITYPLUGIN_VALIDATINGASSETS = "Validating Assets...";
		public const string UI_UNITYPLUGIN_MENUABOUT = "About...";
		public const string UI_UNITYPLUGIN_MENUDOCUMENTATION = "Documentation (website)";
		public const string UI_UNITYPLUGIN_MENUEXTRACTT4TEMPLATES = "Extract T4 Templates";
		public const string UI_UNITYPLUGIN_MENUGENERATECODEANDASSETS = "Generate Code and Assets";
		public const string UI_UNITYPLUGIN_MENURECOVERYSCRIPTS = "Recovery Scripts";
		public const string UI_UNITYPLUGIN_MENUSCANFORNEWASSETS = "Scan for new Assets";
		public const string UI_UNITYPLUGIN_MENUREPORTISSUE = "Report an Issue...";
		public const string UI_UNITYPLUGIN_MENUTROUBLESHOOTING = "Troubleshooting";
		public const string UI_UNITYPLUGIN_MENUVALIDATEASSETS = "Validate Assets";
		public const string UI_UNITYPLUGIN_MENUVERBOSELOGS = "Verbose Logs";
		public const string UI_UNITYPLUGIN_OPERATIONCANCELLED = "Operation was cancelled by user.";
		public const string UI_UNITYPLUGIN_WINDOWABOUTCHARONTITLE = "Charon: Game Data Editor";
		public const string UI_UNITYPLUGIN_WINDOWACTIONSGROUP = "Actions";
		public const string UI_UNITYPLUGIN_WINDOWASSETGENERATIONPATH = "Asset Generation Path";
		public const string UI_UNITYPLUGIN_WINDOWAUTOGENERATION = "Auto-Generation";
		public const string UI_UNITYPLUGIN_WINDOWBROWSEBUTTON = "Browse...";
		public const string UI_UNITYPLUGIN_WINDOWBROWSER = "Browser";
		public const string UI_UNITYPLUGIN_WINDOWBROWSERPATH = "Browser Path";
		public const string UI_UNITYPLUGIN_WINDOWBROWSERPATHTITLE = "Path to browser application";
		public const string UI_UNITYPLUGIN_WINDOWCANCELBUTTON = "Cancel";
		public const string UI_UNITYPLUGIN_WINDOWCHECKINGMONO = "Checking Mono...";
		public const string UI_UNITYPLUGIN_WINDOWCHECKINGMONOFAILED = "Mono doesn't return any version information. Exit code: {0}";
		public const string UI_UNITYPLUGIN_WINDOWCHECKINGVERSION = "Checking...";
		public const string UI_UNITYPLUGIN_WINDOWCHECKRESULTMISSINGMONOORDOTNET = "Missing .NET Runtime!";
		public const string UI_UNITYPLUGIN_WINDOWCHECKRESULTMISSINGTOOLS = "Missing Tools!";
		public const string UI_UNITYPLUGIN_WINDOWCODEENTRYCLASSNAME = "Code Entry class";
		public const string UI_UNITYPLUGIN_WINDOWCODEGAMEDATACLASSNAME = "Code GameData class";
		public const string UI_UNITYPLUGIN_WINDOWCODEGENERATIONPATH = "Code Generation Path";
		public const string UI_UNITYPLUGIN_WINDOWCODEGENERATOR = "Code Generator";
		public const string UI_UNITYPLUGIN_WINDOWCODEIDENTATION = "Identation";
		public const string UI_UNITYPLUGIN_WINDOWCODELINEENDINGS = "Line endings";
		public const string UI_UNITYPLUGIN_WINDOWCODENAMESPACE = "Code Namespace";
		public const string UI_UNITYPLUGIN_WINDOWCODEOPTIONS = "Options";
		public const string UI_UNITYPLUGIN_WINDOWDOWNLOADDOTNET = "c) Or you can download  .NET 4.5 by pressing 'Download .NET 4.5'.";
		public const string UI_UNITYPLUGIN_WINDOWDOWNLOADDOTNETBUTTON = "Download .NET 4.5";
		public const string UI_UNITYPLUGIN_WINDOWDOWNLOADMONO = "b) If it doesn't exists you can press 'Download Mono' button below and try again.";
		public const string UI_UNITYPLUGIN_WINDOWDOWNLOADMONOBUTTON = "Download Mono";
		public const string UI_UNITYPLUGIN_WINDOWEDITBUTTON = "Edit";
		public const string UI_UNITYPLUGIN_WINDOWEDITORCHECKINGRUNTIME = "Checking runtime and executable...";
		public const string UI_UNITYPLUGIN_WINDOWEDITORCHECKINGLICENSE = "Checking license...";
		public const string UI_UNITYPLUGIN_WINDOWEDITORTITLE = "Editor";
		public const string UI_UNITYPLUGIN_WINDOWEDITORCOPYINGEXECUTABLE = "Copying executable to Temp directory...";
		public const string UI_UNITYPLUGIN_WINDOWFAILEDTOSTARTEDITOR = "Failed to start Game Data editor due errors:";
		public const string UI_UNITYPLUGIN_WINDOWFAILEDTOSTARTEDITORTIMEOUT = "Failed to start Game Data editor due errors: Aborted by timeout.";
		public const string UI_UNITYPLUGIN_WINDOWFINDMONOMANUALLY = "a) You can manually locate Mono Runtime by pressing 'Browse...' button.";
		public const string UI_UNITYPLUGIN_WINDOWGENERATIONPREFIX = "Generation:";
		public const string UI_UNITYPLUGIN_WINDOWHELPBUTTON = "Help";
		public const string UI_UNITYPLUGIN_WINDOWIMPORTLICENSEBUTTON = "Import";
		public const string UI_UNITYPLUGIN_WINDOWINFOGROUP = "Info:";
		public const string UI_UNITYPLUGIN_WINDOWLICENSEHOLDER = "License Holder";
		public const string UI_UNITYPLUGIN_WINDOWLICENSEKEY = "License Key";
		public const string UI_UNITYPLUGIN_WINDOWLOADINGFAILEDWITHERROR = "Loading failed with error: {0}";
		public const string UI_UNITYPLUGIN_WINDOWOKBUTTON = "Ok";
		public const string UI_UNITYPLUGIN_WINDOWPATHTOMONO = "Path to Mono (bin)";
		public const string UI_UNITYPLUGIN_WINDOWPRESSHELP = "If you need a help with .NET Runtime installation press 'Help' button.";
		public const string UI_UNITYPLUGIN_WINDOWRECHECKBUTTON = "Re-check";
		public const string UI_UNITYPLUGIN_WINDOWRELOADBUTTON = "Reload";
		public const string UI_UNITYPLUGIN_WINDOWRESUMECODERECOMPILATION = "Resume code re-compilation?";
		public const string UI_UNITYPLUGIN_WINDOWRUNGENERATORBUTTON = "Run Generator";
		public const string UI_UNITYPLUGIN_WINDOWRUNTIMEREQUIRED = "To run Game Data Editor and related tools you need a installed .NET Runtime or Mono Runtime.";
		public const string UI_UNITYPLUGIN_WINDOWRUNTIMEVERSION = "Runtime Version";
		public const string UI_UNITYPLUGIN_WINDOWRUNTIMEVERSIONERROR = "Error";
		public const string UI_UNITYPLUGIN_WINDOWRUNTIMEVERSIONUNKNOWN = "Unknown";
		public const string UI_UNITYPLUGIN_WINDOWSETTINGSGROUP = "Settings:";
		public const string UI_UNITYPLUGIN_WINDOWTOOLSPATH = "Tools Path";
		public const string UI_UNITYPLUGIN_WINDOWTOOLSPORT = "Tools Port";
		public const string UI_UNITYPLUGIN_WINDOWTOOLSVERSIONLABEL = "Tools Version";
		public const string UI_UNITYPLUGIN_WINDOWUNTRACTBUTTON = "Untrack";
		public const string UI_UNITYPLUGIN_WINDOWUPDATERUNTIMETITLE = ".NET Runtime Update";
		public const string UI_UNITYPLUGIN_WINDOWUPDATETOOLSTITLE = "Tools Update";
		public const string UI_UNITYPLUGIN_WINDOWVALIDATEBUTTON = "Validate";
		public const string UI_UNITYPLUGIN_WINDOWVALIDATIONPREFIX = "Validation:";
		public const string UI_UNITYPLUGIN_MENUCHECKRUNTIME = "Check Runtime Version...";
		public const string UI_UNITYPLUGIN_WINDOWLASTTOOLSVERSIONLABEL = "Last Tools Version";
		public const string UI_UNITYPLUGIN_MENUCHECKUPDATES = "Check for Updates";
		public const string UI_UNITYPLUGIN_PROGRESSCHECKINGTOOLSVERSION = "Checking current tools version...";
		public const string UI_UNITYPLUGIN_PROGRESSDOWNLOADINGS = "Downloading assets ({0:F2}/{1:F2}Mib)...";
		public const string UI_UNITYPLUGIN_PROGRESSGETTINGAVAILABLEBUILDS = "Getting list of public releases...";
		public const string UI_UNITYPLUGIN_ATTACHFILEBUTTON = "Attach...";
		public const string UI_UNITYPLUGIN_SELECTFILETOATTACHTITLE = "Select file to attach";
		public const string UI_UNITYPLUGIN_REPORTBUTTON = "Report";
		public const string UI_UNITYPLUGIN_WINDOWATTACHFILECHECKBOX = "Attach '{0}' file ({1:F2}Mb)";
		public const string UI_UNITYPLUGIN_WINDOWREPORTERLABEL = "Your E-Mail or Name";
		public const string UI_UNITYPLUGIN_WINDOWREPORTISSUETITLE = "Report an Issue";
		public const string UI_UNITYPLUGIN_WINDOWTYPELABEL = "Type";
		public const string UI_UNITYPLUGIN_WINDOWREPORTTHANKSMESSAGE = "Thank you for your feedback!";
		public const string UI_UNITYPLUGIN_DOWNLOADBUTTON = "Update (~10 MiB)";
		public const string UI_UNITYPLUGIN_UPDATEAVAILABLEMESSAGE = "A new vesion '{1}' of tools available. Current version is '{0}'.";
		public const string UI_UNITYPLUGIN_UPDATEAVAILABLETITLE = "Update Charon";
		public const string UI_UNITYPLUGIN_WINDOWASSETSTOREINVOICENUMBER = "Asset Store Invoice Number";
		public const string UI_UNITYPLUGIN_WINDOWBACKBUTTON = "Back";
		public const string UI_UNITYPLUGIN_WINDOWEMAIL = "Email";
		public const string UI_UNITYPLUGIN_WINDOWEXPIRATION = "Expiration";
		public const string UI_UNITYPLUGIN_WINDOWFIRSTNAME = "First Name";
		public const string UI_UNITYPLUGIN_WINDOWLASTNAME = "Last Name";
		public const string UI_UNITYPLUGIN_WINDOWLICENSEACTIVATIONTITLE = "Charon License Activation";
		public const string UI_UNITYPLUGIN_WINDOWNOAVAILABLELICENSESMESSAGE = "No available licenses.";
		public const string UI_UNITYPLUGIN_WINDOWORGANIZATION = "Organization";
		public const string UI_UNITYPLUGIN_WINDOWORGANIZATIONID = "Organization Id";
		public const string UI_UNITYPLUGIN_WINDOWPASSWORD = "Password";
		public const string UI_UNITYPLUGIN_WINDOWPASSWORDSDOESNMATCHMESSAGE = "Password does not match.";
		public const string UI_UNITYPLUGIN_WINDOWRECIPIENTID = "Recipient Id";
		public const string UI_UNITYPLUGIN_WINDOWREGISTERBUTTON = "Register";
		public const string UI_UNITYPLUGIN_WINDOWRETYPEPASSWORD = "Re-Type Password";
		public const string UI_UNITYPLUGIN_WINDOWSELECTLICENSELABEL = "Select License";
		public const string UI_UNITYPLUGIN_WINDOWSERIALNUMBER = "Serial Number";
		public const string UI_UNITYPLUGIN_WINDOWSIGNINBUTTON = "Sign In";
		public const string UI_UNITYPLUGIN_WINDOWTYPE = "Type";
		public const string UI_UNITYPLUGIN_WINDOWEDITORLAUNCHINGEXECUTABLE = "Launching editor's executable...";
		public const string UI_UNITYPLUGIN_WINDOWEDITOROPENINGBROWSER = "Opening brower...";
		public const string UI_UNITYPLUGIN_CHANGEBUTTON = "Change...";
		public const string UI_UNITYPLUGIN_MENUOPENLOGS = "Open Logs";
#endif
	}
}

