//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

using System;
using GameDevWare.Charon;
using JetBrains.Annotations;
using UnityEngine;

namespace Assets.Scripts
{
	[PublicAPI, Serializable]
	public class ProjectSettingDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.ProjectSetting.SchemaName;

		[CanBeNull]
		public Assets.Scripts.ProjectSetting GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.ProjectSetting>();
		}
	}

	[PublicAPI, Serializable]
	public class ParameterDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Parameter.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Parameter GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Parameter>();
		}
	}

	[PublicAPI, Serializable]
	public class ParameterValueDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.ParameterValue.SchemaName;

		[CanBeNull]
		public Assets.Scripts.ParameterValue GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.ParameterValue>();
		}
	}

	[PublicAPI, Serializable]
	public class ProvisionDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Provision.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Provision GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Provision>();
		}
	}

	[PublicAPI, Serializable]
	public class HeroDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Hero.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Hero GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Hero>();
		}
	}

	[PublicAPI, Serializable]
	public class ItemDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Item.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Item GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Item>();
		}
	}

	[PublicAPI, Serializable]
	public class LocationDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Location.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Location GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Location>();
		}
	}

	[PublicAPI, Serializable]
	public class TrinketDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Trinket.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Trinket GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Trinket>();
		}
	}

	[PublicAPI, Serializable]
	public class MonsterDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Monster.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Monster GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Monster>();
		}
	}

	[PublicAPI, Serializable]
	public class LootDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Loot.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Loot GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Loot>();
		}
	}

	[PublicAPI, Serializable]
	public class CombatEffectDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.CombatEffect.SchemaName;

		[CanBeNull]
		public Assets.Scripts.CombatEffect GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.CombatEffect>();
		}
	}

	[PublicAPI, Serializable]
	public class CurioCleansingOptionDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.CurioCleansingOption.SchemaName;

		[CanBeNull]
		public Assets.Scripts.CurioCleansingOption GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.CurioCleansingOption>();
		}
	}

	[PublicAPI, Serializable]
	public class CurioDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Curio.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Curio GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Curio>();
		}
	}

	[PublicAPI, Serializable]
	public class DiseaseDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Disease.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Disease GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Disease>();
		}
	}

	[PublicAPI, Serializable]
	public class QuirkDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Quirk.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Quirk GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Quirk>();
		}
	}

	[PublicAPI, Serializable]
	public class ConditionDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Condition.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Condition GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Condition>();
		}
	}

	[PublicAPI, Serializable]
	public class WeaponDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Weapon.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Weapon GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Weapon>();
		}
	}

	[PublicAPI, Serializable]
	public class ArmorDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.Armor.SchemaName;

		[CanBeNull]
		public Assets.Scripts.Armor GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.Armor>();
		}
	}

	[PublicAPI, Serializable]
	public class ItemWithCountDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.ItemWithCount.SchemaName;

		[CanBeNull]
		public Assets.Scripts.ItemWithCount GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.ItemWithCount>();
		}
	}

	[PublicAPI, Serializable]
	public class StartingSetDocumentReference: GameDataDocumentReference
	{
		[SerializeField]
		public string predefinedSchemaNameOrId = Assets.Scripts.StartingSet.SchemaName;

		[CanBeNull]
		public Assets.Scripts.StartingSet GetReferencedDocument()
		{
			return this.GetReferencedDocument<Assets.Scripts.StartingSet>();
		}
	}


}
